version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
